/**
 * ExtensionManager — resolves the bundled TMWD Chrome extension path
 * and generates config.js with a unique session token.
 */

import { writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { logger } from '@utils/logger';

const EXTENSION_DIR_NAME = 'tmwd-extension';

export class ExtensionManager {
  private extensionPath: string | null = null;

  /**
   * Get the absolute path to the bundled Chrome extension directory.
   * Creates config.js with a fresh TID if it doesn't exist.
   */
  getExtensionPath(): string {
    if (this.extensionPath) return this.extensionPath;

    // Try multiple candidate locations
    const candidates = [
      // Built dist (compiled)
      resolve(__dirname, '..', '..', 'assets', EXTENSION_DIR_NAME),
      // Source (tsx/dev)
      resolve(__dirname, '..', '..', '..', 'src', 'assets', EXTENSION_DIR_NAME),
      // Package root
      resolve(process.cwd(), 'src', 'assets', EXTENSION_DIR_NAME),
    ];

    for (const candidate of candidates) {
      const manifestPath = join(candidate, 'manifest.json');
      if (existsSync(manifestPath)) {
        this.extensionPath = candidate;
        this.ensureConfigJs(candidate);
        return candidate;
      }
    }

    throw new Error(
      `TMWD extension not found. Searched:\n${candidates.map((c) => `  - ${c}`).join('\n')}`,
    );
  }

  /**
   * Generate config.js with a unique TID for this session.
   */
  ensureConfigJs(extensionDir?: string): string {
    const dir = extensionDir ?? this.extensionPath;
    if (!dir) throw new Error('Extension path not resolved');

    const configPath = join(dir, 'config.js');
    const tid = '__jshook_' + randomBytes(4).toString('hex');
    const content = `// Auto-generated by jshookmcp — do not edit.\nconst TID = '${tid}';\n`;

    writeFileSync(configPath, content, 'utf-8');
    logger.debug(`[extension] Generated config.js with TID=${tid}`);
    return configPath;
  }

  /**
   * Run diagnostics on the extension setup.
   */
  doctor(): {
    extensionPath: string | null;
    configJsExists: boolean;
    manifestExists: boolean;
    nextSteps: string[];
  } {
    const nextSteps: string[] = [];
    let extensionPath: string | null = null;
    let configJsExists = false;
    let manifestExists = false;

    try {
      extensionPath = this.getExtensionPath();
      manifestExists = existsSync(join(extensionPath, 'manifest.json'));
      configJsExists = existsSync(join(extensionPath, 'config.js'));
    } catch {
      nextSteps.push('Extension assets not found. Ensure src/assets/tmwd-extension/ exists.');
    }

    if (extensionPath) {
      nextSteps.push(
        `Load the unpacked extension from: ${extensionPath}`,
        'Open chrome://extensions → Enable Developer Mode → Load unpacked',
        'Open a normal http/https page in Chrome (not about:blank)',
      );
    }

    return { extensionPath, configJsExists, manifestExists, nextSteps };
  }
}
